### ISSUE TITLE
Windows Defender (up-to-date WIN10) detects "dfr_updater.exe" as a Trojan

### ISSUE THREAD

**Issue by SR-G** [MalloyDelacroix/DownloaderForReddit#1]
In the latest provided release (zipped dfr 1.1.0 for windows).
Don't know if it is a false positive or not.

![2017-07-09 14_27_32-windows defender](https://user-images.githubusercontent.com/194141/27993935-fe5fb33e-64b2-11e7-96f6-3165aae7498d.png)

**Comment by MalloyDelacroix** [comment]
I can't reproduce this on my computer so I'm not exactly sure what is going on.  I assume your windows defender is set to detect any .exe files that are from an "untrusted source."  

However, since that release I have realized that there is a problem with the updater and it will in fact not work correctly when a new version is released.  Because of this and the ease of installing the program from github anyway, I have decided to remove the updater from the package and opted instead for an update alert.  

Since the updater is no longer included in the application, I am going to mark this a closed.
