### ISSUE TITLE
crashes... log included

### ISSUE THREAD

**Issue by EC-O-DE** [MalloyDelacroix/DownloaderForReddit#104]
{"levelname": "CRITICAL", "name": "DownloaderForReddit.__main__", "filename": "main.py", "module": "main", "funcName": "log_unhandled_exception", "lineno": 86, "message": "Unhandled exception", "asctime": "03/11/2020 07:41:40 AM", "exc_info": "Traceback (most recent call last):\n  File \"DownloaderForReddit\\Core\\Content.py\", line 106, in run\n  File \"DownloaderForReddit\\Core\\Content.py\", line 178, in check_save_path_subreddit\n  File \"DownloaderForReddit\\Utils\\SystemUtil.py\", line 57, in create_directory\n  File \"os.py\", line 220, in makedirs\nOSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'Y:/Reddit/username\t\\t/'"}

{"levelname": "CRITICAL", "name": "DownloaderForReddit.__main__", "filename": "main.py", "module": "main", "funcName": "log_unhandled_exception", "lineno": 86, "message": "Unhandled exception", "asctime": "03/11/2020 07:44:18 AM", "exc_info": "Traceback (most recent call last):\n  File \"DownloaderForReddit\\Core\\Content.py\", line 106, in run\n  File \"DownloaderForReddit\\Core\\Content.py\", line 178, in check_save_path_subreddit\n  File \"DownloaderForReddit\\Utils\\SystemUtil.py\", line 57, in create_directory\n  File \"os.py\", line 220, in makedirs\nOSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'Y:/Reddit/anotherusername\\t\\t/'"}

**Comment by MalloyDelacroix** [comment]
It looks like you have two tab indents at the end of the username.  Try re-entering the name without the tabs.

**Comment by EC-O-DE** [comment]
there's a bracket ( " )at the and of anotherusername\t\t/'"} ....

**Comment by EC-O-DE** [comment]
[WinError 123] The filename, directory name, or volume label syntax is incorrect

[https://stackoverflow.com/questions/33618656/python-windowserror-error-123-the-filename-directory-name-or-volume-label-s]

**Comment by EC-O-DE** [comment]
@MalloyDelacroix

**Comment by MalloyDelacroix** [comment]
I'm afraid I don't follow.  Can you paste the users name exactly as you entered it?

**Comment by EC-O-DE** [comment]
from .exe

and I've added usernames from a text file each to  own line no spaces before or after

**Comment by EC-O-DE** [comment]
when downloading starts to run it recognizes usernames as valid...

**Comment by EC-O-DE** [comment]
Could it be that save files are located c/users/users/someguy.../.
The app itself is located on Z: drive in it's own folder
And downloads goes to Y:/Reddit/

the log clearly states that it cannot create folders to Y:/Reddit/

**Comment by MalloyDelacroix** [comment]
Python can create a folder that is on another drive without issue.  As I said before, I believe the problem is that one of the names in the list you are importing has tab characters after the name.  

The log is reporting the path `Y:/Reddit/anotherusername\t\t/` cannot be created.  The `\t` characters shown are usually represented as a series of spaces, but show as the literal character in the log message.  The error is caused because Windows cannot create a file path with a tab in it.

When supplied to reddit for validation, the server apparently strips the characters then validates.  The name used for folder creation however is the name as you enter it.  This is why the name is making to the folder creation point.

Double check the names in the text file you are importing to make sure there are not any spaces after the names.

**Comment by EC-O-DE** [comment]
did it with notepad++ thtank you very much sorry for bothering :)
