### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by ghost** [MalloyDelacroix/DownloaderForReddit#11]
I have a few suggestions for this great program.

* Automatically save changes to lists (crashes wiped out my lists the first few times before I realised I had to manually save)
* Option to Backup/restore lists
* Selecting "import save file" then cancelling results in an error
* Include a pause/resume button
* Option to exclude subreddit from downloading without removing it from list
* Option to rename subreddits (if a typo is made when entering. have to remove and readd at the moment)
* Allow adding multiple subreddits to lists by pasting from the clipboard instead of one at a time.

Maybe in the future you could make a version which works with 4chan or similar.

**Comment by MalloyDelacroix** [comment]
Thanks, I'm glad you are enjoying the program.  I am always looking for suggestions for improvements.

* For your first two items: 
These are actually going to be side effects of a large change that I am planning for the next major release (v3.0).  This release is still a little ways off, but these features are coming.

* The import save file cancel error:
Thanks for bringing this up.  This will be fixed for the next patch release.

* Option to rename reddit objects:
This was actually a conscious decision to not allow renaming.  The problem with this is after a reddit object has been downloaded, changing the name would result in a lot of errors throughout the application.  After running a download cycle, there is no reason to rename an object anyway as everything on the list has been verified to exist.  The only time that it would be acceptable to rename an object is just after adding it.  I felt that allowing renaming the users/subreddits would cause more problems that having to delete and re-add them.

* The pause button:
This is more or less what happens when you click the download button while the app is downloading.  It's not exactly a true pause, because several actions that happen during the download process can't really be paused.  They must be setup and deconstructed to save certain things that are needed for fluent subsequent runs.  Attempts are made to make this like a pause feature that can even be continued after the app is closed.  Extracted content and gathered posts are saved for future runs.  I don't believe a true pause feature is in the foreseeable future. 

* 4chan version:
This would require a very large architectural change; almost a completely new program.  I won't say this is not in the future, but it will be very far off if it is.

* Option to exclude objects from download run / Adding object lists by pasting:
These are great suggestions.  I will definitely look into adding these into future versions.  Most likely these will be included in the next minor release.

Thanks for all your feedback.

**Comment by MalloyDelacroix** [comment]
The doable features in this request (except the ones scheduled for v3.0) have been incorporated into the application.
