### ISSUE TITLE
Date limit does not work

### ISSUE THREAD

**Issue by TastefulBiscuit** [MalloyDelacroix/DownloaderForReddit#138]
The date limit does not work. Setting the date, applying the setting, and going back into settings shows the date reverting back to 06/23/05 14:43. All other settings can be changed and will stay. Is not affected by 'Match file date to post date' setting

Downloading into an existing folder will create duplicates of some but not all posts. Once downloaded and store in database, it does not download again.

**Environment Information**
 - Windows 10
 - Software version 3.1.1-beta

**To Reproduce**
1. Open settings
2. Change date limit for any list or user and check date limit box
3. Press Apply, then ok
4. Open settings, date limit is unchecked and reverted to 06/23/05 14:43

Side request: redgifs not supported

**Comment by MalloyDelacroix** [comment]
Fixed with #139.

I believe the problem you're having with the duplicate downloads may be due to some content being posted more than once, but at a different url.  Unfortunately, there is no good solution to this problem.  If you believe this is not the case, please open a separate issue.

Redgifs is supported.  I can not replicate an issue with extracting links hosted by redgifs.  If this problem persists, please open a new issue and attach your log file.
