### ISSUE TITLE
macOS support?

### ISSUE THREAD

**Issue by 12-Seconds** [MalloyDelacroix/DownloaderForReddit#166]
Would it be possible to make this software run on macOS?

**Comment by zacker150** [comment]
The main issue is that you need a Mac to develop software for a Mac.

**Comment by 12-Seconds** [comment]
I've built it from source, and it works. How did you package the app into an exe?

**Comment by MalloyDelacroix** [comment]
We use Pyinstaller to package the app.  There is a script in the main project directory named "build_venv.spec".  This is the Pyinstaller spec file used to build the app. For more information on the build process, [here is the Pyinstaller manual](https://pyinstaller.readthedocs.io/en/stable/).

Due to what zacker150 pointed out about needing a Mac to develop for MacOS, building an executable for MacOS is not an issue that is likely to be resolved.  However; it should function properly when built from source, except for a few display quirks.
