### ISSUE TITLE
Issues with export user list

### ISSUE THREAD

**Issue by T-prog3** [MalloyDelacroix/DownloaderForReddit#179]
1. If you go to Lists > Export User List and choose CSV then you will end up with a csv-file without any users in it even if you have lots of users in your active list.

2. If you go to Lists > Export User List and choose JSON and Export completed nested objects you will end up with a software crash when you press finish

**Comment by MalloyDelacroix** [comment]
The CSV export process is unclear without a user manual at the moment.  If you use the export option in the main toolbar menu, you are actually only exporting the "list" data, since the list which contains users/subreddits is a database model object as well.  CSV exports are not nested, so the export will not contain the users in the list.  To export the users, select all of the users you wish to export and select export users from the context menu.

The nested JSON export should work as expected from the toolbar menu.  Can you attach your log file for this issue?

**Comment by T-prog3** [comment]
As you say it's a bit unclear because the logical conclusion would be that you export full content of the active list. As with the other alternatives in the Lists menu, you add a whole new list or remove a whole list.In the same way it's logical to select specified users and your action in the context menu would affect only selected users.

The only part of JSON export that seems to work is the "Export names of nested objects only" The other alternative result in a crash. 

Here is the Log:
[DownloaderForReddit.log](https://github.com/MalloyDelacroix/DownloaderForReddit/files/5597824/DownloaderForReddit.log)
