### ISSUE TITLE
Portable, not installed on C, save_file.dat...

### ISSUE THREAD

**Issue by EC-O-DE** [MalloyDelacroix/DownloaderForReddit#20]
Could it be possible to determine location where to save save_file.dat?

Some stuff I don't want to keep on Windows partition as Windows gets clean installed few times a year. So it's better to not have files there - easier & faster & safer.

**Comment by MalloyDelacroix** [comment]
This should be fairly easy to implement.  I will try to include it in the next release.

**Comment by EC-O-DE** [comment]
This would be helpful as I have 3.0 on removable marked drive so it cannot save to c:/users/.../.../..
Also I created a NTFS junction from from that C: ^ location to the same drive where the app is running and while it seems that importing would work... user/sublist is not populating to the main view (not even after reinstall).

**Comment by MalloyDelacroix** [comment]
It has been decided that this issue will not be fixed.  Moving forward, settings will now be stored in a configuration file instead of on the windows registry.  While this makes the application more portable, it means that the data directory location has to be hard coded since it's location would need to be read from this config file if it were user customizable.  

It should be as simple as coping and pasting the database and settings file if things need to be backed up or moved to another system.
