### ISSUE TITLE
Crashing during validation with InvalidTokenException

### ISSUE THREAD

**Issue by MalloyDelacroix** [MalloyDelacroix/DownloaderForReddit#21]
Downloader suddenly crashes during validation phase.  The log reports a Critical level entry caused by: prawcore.exceptions.InvalidToken: received 401 HTTP response.

**Comment by Chrisnetika** [comment]
I reduced the setting "number of simultaneous download threads" setting from 4 to 1 to try to rid this issue and it just as much worse.So today instead I tried to set this from 1 to 8 and I haven't had that issue since (knocks on wood).I have a user list of about 150 right now and that error is very frustrating.So far so good, perhaps this can help pinpoint the issue.I know I been keeping you busy lol but at least the app is getting better.Also more threads the downloads seem go even faster compared to 1 when it's slow.
I like 2.3.0 despite the new issues but solves couple old ones that were crippling.New video downloader is good, just need tweaks and you already fixed imgur credit issues so it's on the right track.

**Comment by MalloyDelacroix** [comment]
This issue seems to have disappeared in recent versions.  This will be closed for now.
