### ISSUE TITLE
Score Limit Eval preventing future Post Downloads?

### ISSUE THREAD

**Issue by iratekalypso** [MalloyDelacroix/DownloaderForReddit#228]
Currently, I have recently been running a scheduled download each hour with these settings.
![image](https://user-images.githubusercontent.com/64004674/125757902-3c2c7867-54ab-4c0e-8e34-0c4092c19ce8.png)

I'm assuming it will:
- search through 1000 posts (max API limitation).
- Check if the post has 50 or more upvotes
- Searching through the "**TOP WEEK**" filter

My concern is this... say a post gets shared right before the hourly download. Say it has only 25 upvotes, it won't be downloaded and will be skipped over.

Will it also be skipped over for all future downloads then? Or will the score be checked once more to see if it has reached 50 upvotes yet?
I am for sure missing some posts throughout the day, that eventually reached 50+ upvotes. So it seems like they are currently being skipped.

**Comment by MalloyDelacroix** [comment]
The expected behavior you described is correct for the settings shown.  A post that does not meet the score filter will not be extracted, so there is no record of its url or reddit id to be avoided in future downloads.  

However, if the url of the content that is linked to in the post has been downloaded in a previous session, the post will be extracted and stored in the database but the content will not be downloaded since it is a duplicate.  In my experience, this is a very common reason that people think they are missing downloads.  There are a lot of duplicates on reddit.

The only other reason I can see that you would be missing downloads in this circumstance is if this is a busy subreddit and during the hour between downloads more than 1,000 posts reach the score threshold.  In this case, the post that was skipped the first time for not having a high enough score may be pushed out of the post limit bounds by posts that are ranked higher.  If this is the issue, you could try adjusting the schedule to run more frequently.

If you don't feel like either of these are the cause of your issue, you can submit your log file and I will try to diagnose it.  You can email the log file to downloaderforreddit@gmail.com if you don't want to post it publicly.
