### ISSUE TITLE
Keep Using Credits For Downloaded Content

### ISSUE THREAD

**Issue by Chrisnetika** [MalloyDelacroix/DownloaderForReddit#23]
I like the app but it 's getting annoying when my hourly user credits get burned each time I download users with avoid duplicates on.Thought the purpose for it was to remember what content it downloaded and save it in a database this way next time I download it knows better to make a call for it.Literally when my hourly credits reset I am left with just 50 credits (from 500) just to download 6 imgur pics.I notice credits burn and nothing is downloaded.

**Comment by MalloyDelacroix** [comment]
Avoid duplicates does store a list of downloaded urls for each user/subreddit so that they won't be re-downloaded.  The problem with the imgur credits is, the urls that are stored are the actual download urls that are extracted from an imgur album or container.  So the app has to extract the url to know not to download it.  This problem is overcome by using the "Enforce User Date Limits" option in the settings dialog.  This option picks up the post date on the reddit side and will not extract or download any content before the last downloaded post date.

If you are not using this option, I recommend that you do.  It was intended for a continued download "subscription" like use.  If you are already using this option, then there may be another problem somewhere else that needs to be addressed.

**Comment by Chrisnetika** [comment]
I tried that option, behavior the same if not worse at times.Some reason it seems download is ignoring such preferences.

**Comment by Chrisnetika** [comment]
Version 2.3.0 appears to fix it
Only time I see a credit drain is with a new issue I will post later and even so happens here and there for small amount.
Enforce user date limits seems to be working so far
