### ISSUE TITLE
Can't execute

### ISSUE THREAD

**Issue by EC-O-DE** [MalloyDelacroix/DownloaderForReddit#3]
I try to execute the app but I get an error message: "failed to execute script main". How to solve?

Windows 10.

**Comment by MalloyDelacroix** [comment]
The problem seems to be that what ever folder the executable package is located in will not give the application permission to create the save file that it needs to run.  This seems to only happen from a package that has been zipped though, which is why I didn't catch this before release.

I am working on finding a permanent solution to the problem.  For the meantime, there are a couple temporary solutions that I have found.

If you happen to have an old save file from another version, if you copy that file into the directory with the executable file it should load.  Also, if you will move the executable package to your Downloads folder, that seems to work also.  The application has permission to the Downloads folder for some reason.

**Comment by EC-O-DE** [comment]
I have the old save file... Changing folders doesn't seem to alleviate the issue..

**Comment by EC-O-DE** [comment]
Update?

**Comment by MalloyDelacroix** [comment]
I'm still working on finding a solution.  I have not had much luck in finding out what may be causing the problem.

**Comment by MalloyDelacroix** [comment]
I believe this issue is solved. 

If you would, please download the newest release (v2.0.1) and verify that it has solved your issue.

**Comment by EC-O-DE** [comment]
Yes it's solved.

For a moment I thought that the issue was unzipper that I used - PeaZip/7zip..... But now with WinRAR :)
