### ISSUE TITLE
Issue with naming token

### ISSUE THREAD

**Issue by T-prog3** [MalloyDelacroix/DownloaderForReddit#308]
**Is your feature request related to a problem? Please describe.**
You have a naming token called `%[date_posted]` but this download files as Day-Month-Year, and i cant imagine a useful case were you would want this structure because it means that you will have to look through every 01 Day every Month * Year until you get to day 02 and so on. 

**Describe the solution you'd like**
I think it would make more sense to have it Year-Month-Day so that posts gets grouped correctly and not mixed all over.

**Comment by MalloyDelacroix** [comment]
That token pulled the date format from your settings, found under the "Display" section.  It did, however, use the date time format instead of the date format, which created problematic path names.  

The date token now pulls the format from the date format setting and a new token has been added to use the date time setting if so desired.
