### ISSUE TITLE
v3.15.1 crash at Startup

### ISSUE THREAD

**Issue by QbiX90** [MalloyDelacroix/DownloaderForReddit#316]
- Upgraded from 3.15.0

Run  DownloaderForReddit.exe -> 
![image](https://user-images.githubusercontent.com/36821536/196747839-fb268881-85f7-4ef8-a410-efb06b5b30ee.png)

**Comment by serveral1** [comment]
same error here

**Comment by MalloyDelacroix** [comment]
I'm not sure what caused this.  It appears to only be a packaging error and only happens when the app is compiled with github actions.  Everything works fine when run from source or compiled locally.

I removed the faulty release asset and replaced it with a locally compiled one that works.  This should at least solve the problem for now.
