### ISSUE TITLE
Can not download videos from redgifs.com: "ERROR: Failed to locate content"

### ISSUE THREAD

**Issue by AmperAndSand** [MalloyDelacroix/DownloaderForReddit#317]
**Describe the bug**
v3.15.1 can not download videos from redgifs.com (NSFW). Log shows: "ERROR: Failed to locate content" for each post that links to redgifs.com. I can view and download Redgifs videos without any issues if using a browser extension. 

After v3.15.1 was released, yt-dlp also cannot download from Redgifs. (I believe that [DownloaderForReddit uses the same method that yt-dlp uses to download Redgifs videos](https://github.com/MalloyDelacroix/DownloaderForReddit/issues/312#issuecomment-1284235128).) It seems that something changed on Redgifs' end. There is a fix for yt-dlp mentioned in this issue report: https://github.com/yt-dlp/yt-dlp/issues/5311 that could also be used in DownloaderForReddit.

**Environment Information**
 - Windows 10
 - v3.15.1
 - Compiled version

**To Reproduce** (optional)
1. Attempt to download the content of a user who posted a video from redgifs.com
2. Notice that all posts that link to redgifs.com give out an "ERROR: Failed to locate content" error message in the log and that no redgifs.com videos are downloaded.

**For all but the most trivial of issues, please attach the latest log file.**

It includes NSFW content, so I'll just send it through email if required.

**Comment by zerohero25** [comment]
Hello I am having the same problem please look into this! thx

**Comment by kaboz666** [comment]
I got same problem on newset version, cant download from redgifs.com

**Comment by MalloyDelacroix** [comment]
I am aware of this issue.  The problem is that we don't use a solution similar to yt-dlp, we actually use yt-dlp to do the extraction.  While they have accepted a pull request with a fix, it is not released yet.  I am unable to incorporate their fix until they release it.  As soon as it's released I fix this issue.

I do, however, expect this issue to keep coming up.  Redgifs is updating their API right now, and they don't seem to be concerned with breaking existing API consumers.  I assume this will keep happening every once in a while until they nail down their final version.

**Comment by MalloyDelacroix** [comment]
Well, never mind.  This is fixed.

**Comment by aminiqmal39** [comment]
It broken again. Well, i have been waiting long enough to get the update. Guess i'm out of luck to just found the outdated project.

**Comment by zerohero25** [comment]
I notice its skipping only redgifs when downloading can you look into this malloy thx
