### ISSUE TITLE
Wont load due to missing attribute

### ISSUE THREAD

**Issue by Chrisnetika** [MalloyDelacroix/DownloaderForReddit#34]
Upgrading from ver: 2.3.0-master commit: 55e87899ec9da4cf73714674d8aa2e3123d8ea50
to
commit: 3ec6f1ea96da65cb5337dfdce46940069fa5b683
 App will no load due to missing attribute error
commit: e63a253f2970210bfd8350a68e0171e9763cf2ea seems to be the suspect

Log:
https://imgur.com/a/8giX6vi

rolling back to last working commit

**Comment by MalloyDelacroix** [comment]
This problem will be unique to people who are running the app from the unreleased source.  Since the fix is to update the version number, I wont fix this with a commit because it would mess up the release versioning scheme.

You can fix this easily on your end:

* Open "version.py" in the main project folder
* Change `__version__ = 'v2.3.0'` to `__version__ = 'v2.3.1'` and save the file
* Run the app
* Without doing anything else, save and close
* Change `__version__` back and save it

**Comment by Chrisnetika** [comment]
ok that worked ty
