### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by Chrisnetika** [MalloyDelacroix/DownloaderForReddit#38]
version: 2.3.1?-master 
commit: 842be613294623f173c4e919a6d3f66f17b2341a
python: 3.7.0-stable windows

https://imgur.com/a/z7pCizh

I changed the version.py like last time and it didn't work

**Comment by MalloyDelacroix** [comment]
The project structure has been changed and the app can no longer be ran from the DownloaderForReddit sub directory.  The app will now need to be run from the main project folder (looks like it is "DownloaderForReddit-master" in your case).  

According to the screen shot you attached you are running main.py from the DownloaderForReddit sub directory.  You should be getting a Windows "no such file or directory" error since main.py is no longer located in that directory.  I would recommend downloading a new zip of the application and making sure the structure matches the one shown on the main page.
