### ISSUE TITLE
3rd party Reddit backup pholder_dot_com

### ISSUE THREAD

**Issue by EC-O-DE** [MalloyDelacroix/DownloaderForReddit#39]
It caches tons of Reddit subreddits. urls are similar as on actual Reddit domain - like `pholder.com/r/feminism` AND user pages like: `pholder.com/u/feminist`

^ just an example ^ could it be possible for this app to check pholder_dot_com/* if it has /r/ or /u/ content cached (pholder_dot_com can go years back.. :D) and possibly DL if usual places are empty?

Or provide links of non-downloaded but available content on DFR's user page? The log can become overwhelming to read and copy paste links..

Just ideas!

**Comment by MalloyDelacroix** [comment]
The DownloaderForReddit uses [praw](https://github.com/praw-dev/praw) for its connection to reddit.  This makes it hard to extract links from sites that aren't reddit, even if the urls are very similar.  This may be a feature in a distant future release, but at the moment pulling content from sites other than reddit is not a goal of the project.

The second item you requested has actually already been incorporated into the master branch of the project.  It is still unreleased at the moment, but can be used if the application is run from source.

The failed downloads dialog has been greatly expanded to provide a good look at what failed to download, all of the reddit information (user, subreddit, date posted, score), why it failed, and if the post was saved for future download.  There is a list of all the failed downloads.  Clicking an item opens a second part of the dialog with an expand view of the selected posts data.

This dialog now also has the ability to export the list of failed downloads in text, json, or xml format so that the links can be easily read by other programs.
