### ISSUE TITLE
Crashes on save settings

### ISSUE THREAD

**Issue by sewil** [MalloyDelacroix/DownloaderForReddit#4]
Just trying to save settings without changing anything and it crashes lmao. Also why is the default save path C:\Users\\&lt;user&gt;/Downloads/. Windows 7 btw
![https://vgy.me/DF1Mum.png](https://vgy.me/DF1Mum.png)

**Comment by MalloyDelacroix** [comment]
This is a known issue for which a solution is currently being worked on.  It involves Windows permissions changing for the executable after it is unzipped.  

As for the default save path: I assume you're asking why there are two different types of slashes in the path.  This is because Windows separates its paths with a backslash whereas every other OS separates their paths with a forward slash.  At first this app was tested on Linux where the paths all displayed correctly.

In that particular instance, the reason that there are two different kinds of slashes in the default save path is because to get the users home directory pythons os.path.expanduser("~") is used which takes the OS standard path separator. This is then concatenated with "/Downloads/" to make the full path.  Thus it ended up with the two different slashes. 

I'll change this for future versions.

**Comment by MalloyDelacroix** [comment]
I believe that this issue has been solved.

I would like to ask that you download the newest release (v2.0.1) and verify that this has in fact been solved.
