### ISSUE TITLE
.gifv files...?

### ISSUE THREAD

**Issue by EC-O-DE** [MalloyDelacroix/DownloaderForReddit#44]
Some mp4 / webm files comes as .gifv files to local...?

What to do? Try to re-DL?

**Comment by EC-O-DE** [comment]
hmm I just noticed these .gifv files perhaps those are from the time of thebug.. hmm

**Comment by MalloyDelacroix** [comment]
Are you using the release version V2.2.2?  This issue should have been fixed in July, but that was two months after that version was released.  If you run the application from source this shouldn't be an issue.  If you are running from source and this is an ongoing problem, please reopen this issue.

**Comment by EC-O-DE** [comment]
Yes 2.2.2 - I just recently noticed gifv files few here and there. Good to know that it's fixed!
