### ISSUE TITLE
Any plans on adding multireddit support?

### ISSUE THREAD

**Issue by Multiboxer** [MalloyDelacroix/DownloaderForReddit#5]
DownloaderForReddit works great when downloading from a handful of subreddits at a time but there doesn't seem to be any support for multireddits, when i tried to work around this and add each subreddit manually the program started to crash when a list became greater than ~85 subreddits long. Being able to download relevant images from multiple subreddits in one batch could certainly be quite handy.

**Comment by MalloyDelacroix** [comment]
I never know what multireddit was until I read this.  I will look into supporting this in a future release.

The app should be able to handle many times more than 85 subreddits.  I can't get the results you reported to reproduce on my machine.  I suspect the problem is not in the number of subreddits, but something about the subreddit content or perhaps the action of creating the folder for the subreddit.  If you can attach a text file with the list of subreddits that you are trying to download I can test it and see if I can find the problem.  Or even better, if you are familiar with python and can run the app source code from your command line and send the error to me, that will work also.

**Comment by EC-O-DE** [comment]
I think you would be DL'ing a lot of trivial content... Get to know subreddits and quality posters and mix'n'match em.

For simple webcopy I would recommend: https://www.cyotek.com/cyotek-webcopy

Of course ~ Reddit's multireddit feature is nice and works great on browser and mobile app.

If DFR gets sluggish with tons of subreddits to DL.. As immediate remedy try such as getting only those threads that are above certain score...?

**Comment by MalloyDelacroix** [comment]
From what I can tell with the reddit redesign, I believe multireddits are a thing of the past.  If this changes in the future I will still look into incorporating it into the application.  But for now, it is no longer being considered.  

As for the other problem reported in this issue: if this is still a problem please reopen this issue with an attached log file.
