### ISSUE TITLE
Is there a way to export the list of users ? 

### ISSUE THREAD

**Issue by SaiKDot** [MalloyDelacroix/DownloaderForReddit#54]
I'd like to export the users  from my list in a text or json file. Is there any way that could be done?

**Comment by MalloyDelacroix** [comment]
This feature has been added.  User and subreddit lists can now be exported to text, json, and xml file formats.  When exporting to text files, only the names will be exported.  If exporting to json or xml files, most of the user/subreddits information that can be custom set by the user will also be exported.  The only notable exception is that the previously downloaded urls list will not be exported (due to the resulting file size).  The export options are available through the "Lists" file menu in the main gui.

I've also added the ability to import from json and xml files and restore a user/subreddit's custom set information as it was at the time of export.  These import options are available through the context menu of the add user/subreddit dialogs.

This feature is available now if building from the master branch, otherwise it will show up in the next release, v2.3.3.

Thanks for the suggestion.
