### ISSUE TITLE
Failed to stop

### ISSUE THREAD

**Issue by Bambr-name** [MalloyDelacroix/DownloaderForReddit#57]
STOP button doesn't work at all...  Sometimes it needs hour for stop, sometimes it never stop.

https://i.imgur.com/3g068GO.png

**Comment by MalloyDelacroix** [comment]
I believe the problem is that when a download was stopped all content that had not yet been moved to a download thread was cleared and not allowed to start download, but any running threads that were currently downloading content would be allowed to finish the download.  This meant that if a large file were being downloaded, it could take hours to finish depending on the internet connection.

This has now been changed.  Any content that is being downloaded when the stop signal is sent will be stopped and deleted if not complete.
