### ISSUE TITLE
What are the differences between this tool and NSchradings RedditDataExtractor?

### ISSUE THREAD

**Issue by github-userx** [MalloyDelacroix/DownloaderForReddit#67]

**Comment by MalloyDelacroix** [comment]
I haven't followed that project in many years, but I believe there are many differences.  

Feature wise:
* One of the biggest differences is that this projects GUI is tremendously improved.
* This project is much faster.  It operates extraction and download in separate threads so they may both happen simultaneously.  I'm not sure how reddit Data Extractor handles content downloads, but this project spawns a user determined amount of threads to download content items simultaneously as well.
* reddit Data Extractor's last commit was a little over three years ago, so I don't believe it will download content hosted on reddit, as that is a feature reddit has added in the last couple of years.
* This project allows many settings to be set for individual users/subreddits instead of having to be applied to the whole.
* I believe the reddit Data Extractor does allow text posts and comments to be downloaded.  At this time, this project does not.  We are moving towards that goal, just rather slowly at the moment.

Code wise:
* That project uses PyQt4, this project uses PyQt5.
* The projects share many similar libraries, but this project uses updated versions of almost every one.
* I believe that the code structure of this project is more robust and makes it much more extensible.

The biggest difference in the two though, is that this project is still maintained and (albeit slowly) still under active development.
