### ISSUE TITLE
Import list

### ISSUE THREAD

**Issue by DankMemeGuy** [MalloyDelacroix/DownloaderForReddit#99]
Would be nice to import a user or subreddit list through a textfile

**Comment by zacker150** [comment]
If you right click the add user dialog, the capability is there. 
![image](https://user-images.githubusercontent.com/7518668/74606836-3b1a0200-5099-11ea-8ff8-8cce27939c89.png)

That being said, we should probably update the dialog to include buttons for the import options.

**Comment by MalloyDelacroix** [comment]
I agree, these options should be presented as buttons.  I also like the idea of single and bulk add dialogs.  

If we have two completely separate dialogs, we will have to add another button to the main GUI for bulk adds.  What if instead of doing that, we used the current add user dialog as the single add dialog and left it as the default when the '+' button is clicked.  Then add a 'Bulk Add' button to this dialog which then transforms it into a bigger dialog with all of the import options.  

I know it already somewhat has this functionality by transforming into the list version, but it needs a lot of changes and improvements.

**Comment by zacker150** [comment]
Let's keep this issue open until the new UI has been implemented.

**Comment by MalloyDelacroix** [comment]
I agree.  We'll keep it open.

**Comment by zacker150** [comment]
Here is a proposed design for the new UI: 
![image](https://user-images.githubusercontent.com/7518668/75202451-e4fc2d00-5730-11ea-9cf5-0fd97a0c2876.png)
![image](https://user-images.githubusercontent.com/7518668/75202461-ee859500-5730-11ea-9ff1-05ee25f1c4da.png)

Comments?

**Comment by MalloyDelacroix** [comment]
I like the tabbed window and everything still looks pretty clean.  

The only thing that I would add is an import button.  I'm thinking we just need one button that opens a file select dialog and then handle selecting the importer type in code based on the file extension.  That way we don't have to have four different buttons.

<img width="269" alt="add_users_dialog" src="https://user-images.githubusercontent.com/22173536/75251446-38599400-57a0-11ea-98cf-f3763c1689da.png">

**Comment by MalloyDelacroix** [comment]
This dialog rework as been incorporated into the database_backend branch and will be merged when the database integration is complete.  

I am leaving this here so no one goes down the path of reworking this dialog because the new version is not added to the master branch.
